server:
  port : 8080
  servlet:
    context-path: /v1

management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
spring:
  data:
    mongodb:
      uri: ${MONGO_URI}