name : Deploy on Dev
on : [workflow_dispatch]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      - name : deploy
        run : "Echo deploying with no environment"