name : Deploy on Dev
on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name : deploy
        run : "Echo deploying with no environment"