name : WF Java Testing
on : [push]


jobs:
  junit-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        env:
          MONGODB_USERNAME: test
          MONGODB_PASSWORD: password
          MONGODB_DATABASE: test
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run : mvn test


