name : WF Java Testing
on : [push]


jobs:
  junit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: getong/mongo-action@v1.1
        with:
          mongo version: '4.2-bionic'
          host port: 27017
          mongo username: 'hello'
          mongo password: 'password'
      - name: Set up JDK 17
        uses: actions/setup-java@v3

        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run : mvn test


